docker-compose-yaml: docker-compose.yml

environments:
  master:
    types:
      mariadb: mariadb-shared
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: 'drush cron'
        service: cli
